<?php
// Included inside the isolated archive fixture; all bytes and accounts synthetic.
$cached=app_drive_archive_restore($signedVersion,$get);
$missing=static function(string $object):string{throw new RuntimeException('Synthetic remote object missing');};
drive_reject(static fn()=>app_drive_archive_restore($signedVersion,$missing,true),'fresh cloud verification cannot be satisfied by valid local cache');
drive_check(is_file($cached)&&file_get_contents($cached)===$signed,'failed fresh verification preserves the last authenticated cache');

// A correct local cache must not turn failed remote upload verification into
// success, including when resuming a checkpoint generated by the old worker.
$pendingCurrent=app_drive_archive_current($id,$name,'original');
$fakeCache=app_drive_archive_directory('cache').'/'.$pendingCurrent['id'].'.plain';file_put_contents($fakeCache,$newer);
drive_reject(static fn()=>app_drive_archive_upload_version($pendingCurrent,microtime(true)+30,['put'=>$put,'get'=>$missing]),'cached plaintext never verifies an unavailable remote upload');
$pendingCurrent=app_drive_archive_current($id,$name,'original');
drive_check($pendingCurrent['status']==='pending'&&json_decode($pendingCurrent['parts']??'[]',true)===[],'failed read-back never commits a trusted slice or verified status');
$reads=0;$countedGet=static function(string $object)use($get,&$reads):string{$reads++;return $get($object);};
drive_check(app_drive_archive_upload_version($pendingCurrent,microtime(true)+30,['put'=>$put,'get'=>$countedGet])&&$reads===2,'each new encrypted slice is actually read back before upload completion');
$upgraded=app_drive_archive_current($id,$name,'original');$parts=json_decode($upgraded['parts'],true);
drive_check(count(array_filter($parts,static fn($part)=>($part['readback_verified']??false)===true))===count($parts),'slice verification is checkpointed for resumable progress');

// Recreate an old checkpoint with no per-slice read-back marker. A resume must
// authenticate it, not skip it merely because its declared offset sums correctly.
$spool=app_drive_archive_directory('spool');@link($path,$spool.'/'.$upgraded['id'].'.source');
foreach($parts as &$part)unset($part['readback_verified']);unset($part);
$pdo->prepare("UPDATE eoffice_drive_versions SET status='pending',parts=? WHERE id=?")->execute([json_encode($parts),$upgraded['id']]);
$oldCheckpoint=app_drive_archive_current($id,$name,'original');$reads=0;
drive_check(app_drive_archive_upload_version($oldCheckpoint,microtime(true)+30,['put'=>$put,'get'=>$countedGet])&&$reads===2,'legacy resume checkpoints are authenticated and upgraded even with cached plaintext');

// A signed-file ledger can be newer than a verified pointer. Such a snapshot is
// partial, never a complete recovery set for the wrong signature revision.
$oldLedger=$pdo->prepare('SELECT * FROM eoffice_signed_files WHERE Doc_Id=? AND file_name=?');$oldLedger->execute([$id,$name]);$oldLedger=$oldLedger->fetch();
$pdo->prepare('INSERT INTO eoffice_signed_files (Doc_Id,file_name,revision,signed_at) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE revision=VALUES(revision)')->execute([$id,$name,str_repeat('0',64)]);
$pdo->beginTransaction();try{
    drive_reject(static fn()=>app_drive_archive_snapshot($pdo),'complete snapshot refuses a stale signed revision');
    $partial=app_drive_archive_snapshot($pdo,true);
    drive_check(!$partial['complete_recovery_set']&&$partial['pending_files']===1,'initial snapshot explicitly counts a signed revision mismatch');
}finally{$pdo->rollBack();}
if($oldLedger)$pdo->prepare('UPDATE eoffice_signed_files SET revision=?,signed_at=? WHERE Doc_Id=? AND file_name=?')->execute([$oldLedger['revision'],$oldLedger['signed_at'],$id,$name]);
else $pdo->prepare('DELETE FROM eoffice_signed_files WHERE Doc_Id=? AND file_name=?')->execute([$id,$name]);

// A cached good signature does not allow eviction while its cloud object is
// missing. Supply an eligible complete manifest to reach the fresh read-back.
$pdo->prepare('UPDATE eoffice_drive_versions SET verified_at=DATE_SUB(NOW(),INTERVAL 15 DAY) WHERE id=?')->execute([$signedVersion['id']]);
$eligible=app_drive_archive_current($id,$name,'signed');file_put_contents($signedPath,$signed);
$savedManifest=json_decode($record['manifest'],true);$savedManifest['versions'][$eligible['id']]=$eligible;
$pdo->prepare('UPDATE eoffice_drive_backups SET manifest=? WHERE backup_date=?')->execute([json_encode($savedManifest),$date]);
drive_reject(static fn()=>app_drive_archive_evict($eligible,['put'=>$put,'get'=>$missing]),'eviction fails closed when fresh remote verification fails despite a valid cache');
drive_check(is_file($signedPath)&&hash_file('sha256',$signedPath)===$eligible['revision'],'failed eviction retains the original local signed bytes');unlink($signedPath);

// Three queued files: an accepted-but-timed-out upload, a missing pinned source,
// and a healthy file. The former two cannot starve the healthy file.
$queued=[];
foreach(['retry','broken','healthy'] as $index=>$label){
    $queueName='queue-'.$label.'.pdf';$queuePath=app_storage('original','2566',$queueName);file_put_contents($queuePath,'%PDF-1.4 synthetic '.$label);
    app_document_transaction();app_drive_archive_track($id,$queueName,'original',$queuePath);$pdo->commit();$queued[$label]=app_drive_archive_current($id,$queueName,'original');
    $pdo->prepare('UPDATE eoffice_drive_versions SET created_at=? WHERE id=?')->execute(['2000-01-0'.($index+1).' 00:00:00',$queued[$label]['id']]);
}
unlink($spool.'/'.$queued['broken']['id'].'.source');$failOnce=true;$puts=0;$firstObject=null;
$uncertainPut=static function(string $cipher)use($put,&$failOnce,&$puts,&$firstObject):string{
    $puts++;$object=$put($cipher);
    if($failOnce){$failOnce=false;$firstObject=$object;throw new AppDriveArchiveRetry('Synthetic accepted upload lost its response');}
    return $object;
};
$batch=app_drive_archive_upload_batch(microtime(true)+30,['put'=>$uncertainPut,'get'=>$get]);
drive_check($batch['uploaded']===1&&$batch['retry_pending']===1&&$batch['review_required']===1,'one retryable/broken file never blocks a healthy later upload');
$retry=app_drive_archive_current($id,'queue-retry.pdf','original');$broken=app_drive_archive_current($id,'queue-broken.pdf','original');
drive_check($retry['status']==='pending'&&(int)$retry['attempts']===1&&$retry['retry_at']!==null&&$broken['status']==='review','transient failures back off while broken sources require review');
$before=$puts;$batch=app_drive_archive_upload_batch(microtime(true)+30,['put'=>$uncertainPut,'get'=>$get]);
drive_check($puts===$before&&$batch['uploaded']===0,'backoff prevents immediate retries and review files leave the send queue');
$pdo->prepare('UPDATE eoffice_drive_versions SET retry_at=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE id=?')->execute([$retry['id']]);
$objectCount=count($objects);$batch=app_drive_archive_upload_batch(microtime(true)+30,['put'=>$uncertainPut,'get'=>$get]);$recovered=app_drive_archive_current($id,'queue-retry.pdf','original');
drive_check($batch['uploaded']===1&&$recovered['status']==='verified'&&$recovered['retry_at']===null&&(int)$recovered['attempts']===0,'a later scheduled retry resumes and clears backoff after verification');
drive_check(count($objects)===$objectCount&&json_decode($recovered['parts'],true)[0]['object']===$firstObject,'accepted-but-timed-out retry reuses ciphertext and does not duplicate cloud objects');
$invalid=$recovered;$invalid['bytes']=1;$zero=json_decode($recovered['parts'],true)[0];$zero['bytes']=0;$invalid['parts']=json_encode([$zero]);
drive_reject(static fn()=>app_drive_archive_parts($invalid,true),'non-empty source cannot resume a zero-length checkpoint');
$beforeMigration=(int)$pdo->query('SELECT COUNT(*) FROM eoffice_drive_versions')->fetchColumn();
foreach(['retry_at','attempts','error_code'] as $column)$pdo->exec('ALTER TABLE eoffice_drive_versions DROP COLUMN '.$column);
app_drive_archive_migrate($pdo);app_drive_archive_migrate($pdo);
$columns=array_column($pdo->query('SHOW COLUMNS FROM eoffice_drive_versions')->fetchAll(PDO::FETCH_ASSOC),'Field');
drive_check(count(array_intersect(['retry_at','attempts','error_code'],$columns))===3&&(int)$pdo->query('SELECT COUNT(*) FROM eoffice_drive_versions')->fetchColumn()===$beforeMigration,'retry migration upgrades an existing queue idempotently without losing versions');

// Restoring an older DB can leave a newer same-day spool envelope on disk.
// A retry must reject mixed snapshot pairs rather than publishing a bad set.
$pdo->prepare("UPDATE eoffice_drive_backups SET status='pending',manifest=? WHERE backup_date=?")->execute([$record['manifest'],$date]);
$dailyEnvelope=$spool.'/daily-'.$date.'.ebak';$savedEnvelope=file_get_contents($dailyEnvelope);unlink($dailyEnvelope);
$writer=new AppBackupWriter($dailyEnvelope,app_drive_archive_key($manifest['key_id']),'eoffice-drive-manifest');$writer->write('{"synthetic":"wrong snapshot"}');$writer->finish();unset($writer);
drive_reject(static fn()=>app_drive_archive_backup($transport),'daily retry rejects a valid encrypted manifest from the wrong captured snapshot');
file_put_contents($dailyEnvelope,$savedEnvelope);chmod($dailyEnvelope,0600);
$databasePath=$manifest['database']['path'];$savedDatabase=file_get_contents($databasePath);file_put_contents($databasePath,$savedDatabase.'corrupted');
drive_reject(static fn()=>app_drive_archive_backup($transport),'daily retry rejects a changed encrypted database archive before publication');
file_put_contents($databasePath,$savedDatabase);chmod($databasePath,0600);
$pdo->prepare('UPDATE eoffice_drive_backups SET status=?,error_code=NULL WHERE backup_date=?')->execute([$record['status'],$date]);
