const assert=require('node:assert/strict');
const cp=require('node:child_process');
const path=require('node:path');
const os=require('node:os');
const php=process.env.PHP_BIN||'C:/laragon/bin/php/php-8.3.33-Win32-vs16-x64/php.exe';
const remote=process.env.EOFFICE_STAGING_TEST==='1';
const testPassword=remote?JSON.parse(require('node:fs').readFileSync(path.join(os.homedir(),'AppData/Local/Temp/opencode/eoffice-staging-qa.private.json'),'utf8')).password:'Review-Test-2026!';
const port=Number(process.env.TEST_PORT||8081),base=remote?'https://e-office-test.siya.ac.th':`http://localhost:${port}`;
const env={...process.env,DB_DATABASE:process.env.TEST_DATABASE||'eoffice_review_test',APP_URL:base,EOFFICE_MOCK_SERVICES:'true',EOFFICE_STORAGE:path.join(os.tmpdir(),'opencode','eoffice-test-storage')};
if(!env.DB_DATABASE.endsWith('_test'))throw Error('Test database must end with _test');
function cli(file){if(remote){if(file==='scripts/migrate.php')return '';const action=file==='tests/seed.php'?'seed':'worker';const r=cp.spawnSync('python',['scripts/staging-hosting.py','test-helper',action],{encoding:'utf8'});if(r.status!==0)throw Error(r.stdout+r.stderr);return r.stdout;}const r=cp.spawnSync(php,[file],{env,encoding:'utf8'});if(r.status!==0)throw Error(r.stdout+r.stderr);return r.stdout;}
function inspect(action,value){const r=remote?cp.spawnSync('python',['scripts/staging-hosting.py','test-helper',action,String(value)],{encoding:'utf8'}):cp.spawnSync(php,['tests/inspect.php',action,String(value)],{env,encoding:'utf8'});if(r.status!==0)throw Error(r.stdout+r.stderr);return JSON.parse(r.stdout);}
cli('scripts/migrate.php');const seed=JSON.parse(cli('tests/seed.php'));env.EOFFICE_TEST_AI_RECIPIENTS=JSON.stringify([seed.users.recipient,999999]);
const servers=remote?[]:[0,1,2].map(i=>cp.spawn(php,['-S',`localhost:${port+i}`,'scripts/router.php'],{env:{...env,APP_URL:`http://localhost:${port+i}`},stdio:['ignore','ignore','pipe']}));let serverErrors='';servers.forEach(server=>server.stderr.on('data',s=>serverErrors+=s));
const pdf=Buffer.from(seed.pdf,'base64');let passed=0;const stamp=Date.now();
async function request(route,{cookie='',data,form,method=data||form?'POST':'GET',status=200,headers={},worker=0}={}){
 if(remote)await new Promise(resolve=>setTimeout(resolve,Number(process.env.EOFFICE_REMOTE_DELAY_MS||2000)));
 const r=await fetch((remote?base:`http://localhost:${port+worker}`)+route,{method,redirect:remote?'manual':'follow',headers:{...headers,...(cookie?{Cookie:cookie}:{}),...(data?{'Content-Type':'application/json'}:{})},body:form||(data?JSON.stringify(data):undefined)});
 const text=await r.text();if(remote&&text.includes('One moment, please...'))throw Error(`Hosting bot verification blocked ${route}; no application test result was accepted`);if(Array.isArray(status))assert.ok(status.includes(r.status),`${route}: ${text}`);else assert.equal(r.status,status,`${route}: ${text}`);let body;try{body=JSON.parse(text);}catch{body=text;}return {body,r,text};
}
function form(values,files={}){const f=new FormData();for(const [k,v]of Object.entries(values)){if(Array.isArray(v))v.forEach(x=>f.append(k+'[]',String(x)));else f.append(k,String(v));}for(const [k,v]of Object.entries(files))f.append(k,new Blob([v.data],{type:v.type||'application/pdf'}),v.name);return f;}
async function login(name){const {r}=await request('/api/auth_login.php',{data:{username:`qa-${name}@siya.ac.th`,password:testPassword}});assert.match(r.headers.getSetCookie().join(';'),/HttpOnly/i);return r.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');}
async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
async function run(){
 for(let i=0;i<50;i++){try{await fetch(base+'/api/me.php');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 let admin,owner,recipient,outsider,doc,fileName,revision,roomId,otherRoomId;
 await test('login rejects boolean password',async()=>request('/api/auth_login.php',{data:{username:'qa-admin@siya.ac.th',password:true},status:400}));
 await test('login rejects incorrect password',async()=>request('/api/auth_login.php',{data:{username:'qa-admin@siya.ac.th',password:'wrong'},status:401}));
 await test('roles login and HttpOnly session',async()=>{admin=await login('admin');owner=await login('owner');recipient=await login('recipient');outsider=await login('outsider');});
 await test('guest cannot modify department',async()=>request('/management/save_department_api.php',{form:form({Department_Name:'Unauthorized'}),status:401}));
 await test('ordinary user cannot modify department',async()=>request('/management/save_department_api.php',{cookie:owner,form:form({Department_Name:'Unauthorized'}),status:403}));
 await test('cross-site request rejected',async()=>request('/management/save_department_api.php',{cookie:admin,form:form({Department_Name:'Unauthorized'}),headers:{Origin:'https://attacker.example'},status:403}));
 await test('admin department save and pagination',async()=>{await request('/management/save_department_api.php',{cookie:admin,form:form({Department_Name:'QA '+stamp,Department_Detail:"O'Reilly <img src=x onerror=alert(1)>"})});const {body}=await request('/management/get_departments_api.php?limit=1',{cookie:admin});assert.equal(body.data.length,1);assert.ok(body.total>0);});
 await test('upload PHP-as-PDF rejected atomically',async()=>request('/api/create_document.php',{cookie:owner,form:form({doc_number:'BAD'+stamp,doc_name:'QA',doc_type:'หนังสือ',doc_date_receive:'2026-10-07',doc_file_name:['bad'],file_id:['']},{'doc_upload[]':{data:'<?php echo 1;',name:'bad.pdf'}}),status:400}));
 const values={doc_number:'QA'+stamp,doc_name:'QA landscape document',doc_type:'หนังสือ',doc_date_receive:'2026-10-07',doc_receive_from:'QA',doc_file_name:['Landscape'],file_id:[''],send_to:[seed.users.recipient]};
 await test('document create with recipient and PDF',async()=>{const {body}=await request('/api/create_document.php',{cookie:owner,form:form(values,{'doc_upload[]':{data:pdf,name:'qa.pdf'}})});doc=body.doc_id;assert.ok(doc);const list=await request('/api/get_data_send.php',{cookie:owner,data:{Year:'2569',search_txt:'QA'+stamp}});assert.ok(Array.isArray(list.body),list.text);fileName=list.body[0].doc_upload_path[0].path;});
 await test('private PDF unavailable to guest/outsider',async()=>{await request(`/api/view_file.php?Doc_Id=${doc}&File_Path=${fileName}`,{status:401});await request(`/api/view_file.php?Doc_Id=${doc}&File_Path=${fileName}`,{cookie:outsider,status:403});});
 await test('recipient can read bound PDF with revision',async()=>{const result=await request(`/api/view_file.php?Doc_Id=${doc}&File_Path=${fileName}&Type=signed`,{cookie:recipient});assert.match(result.text,/^%PDF/);revision=result.r.headers.get('X-Document-Revision');assert.ok(revision);});
 await test('read status requires actual access',async()=>{await request('/api/update_read_status.php',{cookie:outsider,data:{doc_id:doc},status:403});await request('/api/update_read_status.php',{cookie:recipient,data:{doc_id:doc}});});
 await test('recipient cannot modify shared document',async()=>{await request('/api/create_document.php',{cookie:recipient,form:form({formtype:'edit_document',doc_id:doc,doc_name:'ATTACK',doc_type:'คำสั่ง',doc_number_receive_stamp:'123'})});const list=await request('/api/get_data_send.php',{cookie:owner,data:{Year:'2569',search_txt:'QA'+stamp}});assert.equal(list.body[0].doc_name,'QA landscape document');});
 await test('signed PDF save and stale revision rejected',async()=>{const f=()=>form({Doc_Id:doc,year:2569,revision},{file:{name:fileName,data:Buffer.concat([pdf,Buffer.from('\n% signed\n')])}});await request('/e-sign/upload_pdf.php',{cookie:recipient,form:f()});await request('/e-sign/upload_pdf.php',{cookie:recipient,form:f(),status:409});});
 await test('rejected signing upload preserves signed state/file',async()=>{const before=await request(`/api/view_file.php?Doc_Id=${doc}&File_Path=${fileName}&Type=signed`,{cookie:owner});await request('/e-sign/upload_pdf.php',{cookie:recipient,form:form({Doc_Id:doc,year:2569,revision:before.r.headers.get('X-Document-Revision')},{file:{name:fileName,data:'not a PDF'}}),status:400});const after=await request(`/api/view_file.php?Doc_Id=${doc}&File_Path=${fileName}&Type=signed`,{cookie:owner});assert.equal(after.r.headers.get('X-Document-Revision'),before.r.headers.get('X-Document-Revision'));assert.equal(inspect('access',doc).find(a=>a.User_Id===seed.users.recipient).Is_Signed,'true');});
 await test('file proxy and retired endpoints denied',async()=>{await request('/api/cors.php?url=file:///etc/passwd',{status:remote?[403,410]:410});await request('/api/uniqid.php',{status:410});await request('/api/create_document-Merhelo.php',{status:410});});
 await test('template upload requires session and actual image',async()=>{await request('/e-sign/save_template.php',{data:{file_name:'test.php',image_data:Buffer.from('<?php echo 1;').toString('base64')},status:401});await request('/e-sign/save_template.php',{cookie:owner,data:{file_name:'test.php',image_data:Buffer.from('<?php echo 1;').toString('base64')},status:400});});
 await test('valid image saved only as server-named PNG',async()=>{const {body}=await request('/e-sign/save_template.php',{cookie:owner,data:{file_name:'payload.php',image_data:seed.png}});assert.equal(body.success,true);assert.match(body.file_path,/\.png$/);assert.ok(inspect('remove_template',body.file_path));});
 await test('foreign attachment ID cannot rename another document file',async()=>{const other=(await request('/api/create_document.php',{cookie:outsider,form:form({...values,doc_number:'FOREIGN'+stamp,send_to:[]},{'doc_upload[]':{name:'qa.pdf',data:pdf}})})).body.doc_id;const list=await request('/api/get_data_send.php',{cookie:outsider,data:{Year:'2569',search_txt:'FOREIGN'+stamp}});const fid=list.body[0].doc_upload_path[0].file_id;await request('/api/create_document.php',{cookie:owner,form:form({...values,formtype:'edit_document',doc_id:doc,file_id:[fid]}),status:403});const unchanged=await request('/api/get_data_send.php',{cookie:outsider,data:{Year:'2569',search_txt:'FOREIGN'+stamp}});assert.equal(unchanged.body[0].doc_id,other);assert.equal(unchanged.body[0].doc_upload_path[0].detail,'Landscape');});
 await test('invalid recipient rolls back whole new document',async()=>{await request('/api/create_document.php',{cookie:owner,form:form({...values,doc_number:'ROLLBACK'+stamp,send_to:[999999],doc_file_name:[],file_id:[]}),status:409});const list=await request('/api/get_data_send.php',{cookie:owner,data:{Year:'2569',search_txt:'ROLLBACK'+stamp}});assert.deepEqual(list.body,[]);});
 await test('notification injection and legacy token rejected',async()=>{await request('/api/create_user_notification.php',{data:{user_token:"' OR 1=1 -- ",target_Id:'valid-subscription-id'},status:401});await request('/api/create_user_notification.php',{cookie:owner,data:{target_Id:"' OR 1=1 -- "},status:400});});
 const booking={requesterName:'QA <img src=x onerror=alert(1)>',roomSelect:'QA room '+stamp,topic:'QA booking',department:'QA',attendees:3,startDate:'2026-10-08',endDate:'2026-10-08',startTime:'10:00',endTime:'11:00',equipment:{}};
 await test('booking creation and owner authorization',async()=>{roomId=(await request('/room_booking/api/room_booking.php',{cookie:owner,data:booking})).body.id;otherRoomId=(await request('/room_booking/api/room_booking.php',{cookie:outsider,data:booking})).body.id;await request('/room_booking/api/update_booking.php',{cookie:outsider,data:{id:roomId},status:403});});
 await test('booking invalid time rejected server-side',async()=>request('/room_booking/api/room_booking.php',{data:{...booking,startTime:'12:00'},status:400}));
 await test('approval overlap and role enforced',async()=>{await request('/room_booking/api/update_status.php',{cookie:owner,data:{id:roomId,status:'confirmed'},status:403});await request('/room_booking/api/update_status.php',{cookie:admin,data:{id:roomId,status:'confirmed'}});await request('/room_booking/api/update_status.php',{cookie:admin,data:{id:otherRoomId,status:'confirmed'},status:409});});
 await test('external numbers unique across parallel PHP workers',async()=>{const results=await Promise.all(Array.from({length:8},(_,i)=>request('/external_number_booking/external_number_booking.php',{cookie:owner,worker:i%3,data:{docDetail:'QA '+i,docYear:2599}})));assert.equal(new Set(results.map(r=>r.body.data.External_Number)).size,8);});
 await test('parallel approval allows exactly one conflicting booking',async()=>{const b={...booking,roomSelect:'QA parallel '+stamp};const a=(await request('/room_booking/api/room_booking.php',{cookie:owner,data:b})).body.id;const c=(await request('/room_booking/api/room_booking.php',{cookie:owner,data:b})).body.id;const results=await Promise.all([a,c].map((id,i)=>request('/room_booking/api/update_status.php',{cookie:admin,data:{id,status:'confirmed'},worker:i,status:[200,409]})));assert.deepEqual(results.map(r=>r.r.status).sort(),[200,409]);});
 await test('guest cannot set maintenance staff state',async()=>{const r=await request('/maintenance_requests/api/submit_maintenance.php',{cookie:owner,data:{requesterName:'QA <img src=x onerror=alert(1)>',requestDate:'2026-10-07',repairTypes:['ไฟฟ้า'],building:'1',room:'1',damageDetails:'QA',phone:'0123456789',considerationStatus:'can_proceed',actionResult:'fixed'}});const list=await request('/maintenance_requests/api/get_maintenance.php?my=true',{cookie:owner});const row=list.body.data.find(x=>x.id===r.body.id);assert.equal(row.consideration_status,'pending');assert.equal(row.action_result,'pending');await request('/maintenance_requests/api/update_maintenance.php',{cookie:owner,data:{id:r.body.id},status:403});});
 await test('mock Drive image and admin maintenance update',async()=>{const r=await request('/maintenance_requests/api/submit_maintenance.php',{cookie:owner,data:{requesterName:'QA image',requestDate:'2026-10-07',repairTypes:['ไฟฟ้า'],building:'1',room:'1',damageDetails:'QA',phone:'0123456789',images:[{filename:'qa.png',mimeType:'image/png',base64Data:seed.png}]}});await request('/maintenance_requests/api/update_maintenance.php',{cookie:admin,data:{id:r.body.id,considerationStatus:'can_proceed',actionResult:'fixed',assignedTo:'QA technician',repairDetails:'QA repaired',materials:[{name:'QA cable',qty:'1'}]}});const list=await request('/maintenance_requests/api/get_maintenance.php?my=true',{cookie:owner});const row=list.body.data.find(x=>x.id===r.body.id);assert.equal(row.action_result,'fixed');assert.match(row.images[0],/mock-/);assert.equal(row.materials[0].name,'QA cable');});
 await test('registration domain and duplicate response',async()=>{await request('/api/register.php',{form:form({register_name:'QA',register_email:'qa@siya.ac.th.attacker.example'}),status:400});await request('/api/register.php',{form:form({register_name:'QA',register_email:'qa-owner@siya.ac.th'}),status:409});});
 await test('registration confirmation and token reuse',async()=>{const email=`qa-signup-${stamp}@siya.ac.th`;await request('/api/register.php',{form:form({register_name:'QA signup',register_email:email})});const token=inspect('registration',email);assert.match(token,/^[a-f0-9]{64}$/);await request('/api/confirm_signup.php',{form:form({token,password:'short'}),status:400});await request('/api/confirm_signup.php',{form:form({token,password:' Signup-Test-2026! '})});assert.equal(inspect('user',email).hashed,true);await request('/api/auth_login.php',{data:{username:email,password:' Signup-Test-2026! '}});await request('/api/confirm_signup.php',{form:form({token,password:'Review-Test-2026!'}),status:400});});
 await test('user create/reset/revoke/delete and pagination',async()=>{const email=`qa-created-${stamp}@siya.ac.th`;await request('/management/new_user_api.php',{cookie:admin,form:form({User_name:'QA created',User_Email:email,User_Status:'User',User_password1:'New-Test-2026!',User_password2:'New-Test-2026!'})});const u=inspect('user',email);assert.equal(u.hashed,true);const lr=await request('/api/auth_login.php',{data:{username:email,password:'New-Test-2026!'}});const cookie=lr.r.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');await request('/management/update_user_api.php',{cookie:admin,form:form({User_Id:u.id,User_name:'QA updated',User_Email:email,User_Status:'User',User_password1:'Updated-Test-2026!',User_password2:'Updated-Test-2026!'})});await request('/room_booking/api/my_bookings.php',{cookie,status:401});await request('/api/auth_login.php',{data:{username:email,password:'Updated-Test-2026!'}});const list=await request('/management/get_users_api.php?limit=1',{cookie:admin});assert.equal(list.body.data.length,1);assert.equal(list.body.data[0].User_Password,undefined);await request('/management/delete_user_api.php',{cookie:admin,form:form({User_Id:u.id})});assert.equal(inspect('user',email),null);});
 await test('group grant visible and revoked signature archived',async()=>{await request('/management/save_department_api.php',{cookie:admin,form:form({Department_Name:'QA group '+stamp})});const groups=await request('/management/get_departments_api.php?search='+encodeURIComponent('QA group '+stamp),{cookie:admin});const dept=groups.body.data[0].Department_Id;await request('/management/update_user_api.php',{cookie:admin,form:form({User_Id:seed.users.outsider,User_name:'QA outsider',User_Email:'qa-outsider@siya.ac.th',User_Status:'User',Department_Id_Acc:[dept]})});await request('/api/create_document.php',{cookie:owner,form:form({...values,formtype:'edit_document',doc_id:doc,doc_file_name:[],file_id:[],send_to:[],send_to_group:[dept],replace_recipients:1})});assert.equal(inspect('access',doc).length,0);assert.equal(inspect('history',doc).find(a=>a.User_Id===seed.users.recipient).Is_Signed,'true');await request(`/api/view_file.php?Doc_Id=${doc}&File_Path=${fileName}`,{cookie:recipient,status:403});await request(`/api/view_file.php?Doc_Id=${doc}&File_Path=${fileName}`,{cookie:outsider});const inbox=await request('/api/get_data_received.php',{cookie:outsider,data:{Year:'2569',Doc_Id:doc}});assert.equal(inbox.body[0].doc_id,doc);});
 await test('editing previous-year document keeps upload year',async()=>{const old=(await request('/api/create_document.php',{cookie:owner,form:form({...values,doc_number:'OLD'+stamp,doc_file_name:[],file_id:[],send_to:[]})})).body.doc_id;inspect('previous_year',old);await request('/api/create_document.php',{cookie:owner,form:form({...values,formtype:'edit_document',doc_id:old,doc_number:'OLD'+stamp,send_to:[]},{'doc_upload[]':{name:'qa.pdf',data:pdf}})});const list=await request('/api/get_data_send.php',{cookie:owner,data:{Year:'2568',search_txt:'OLD'+stamp}});const file=list.body[0].doc_upload_path[0].path;await request(`/api/view_file.php?Doc_Id=${old}&File_Path=${file}&Year=2568`,{cookie:owner});await request(`/api/view_file.php?Doc_Id=${old}&File_Path=${file}&Year=2569`,{cookie:owner,status:403});});
 await test('AI recipients validated, mocked email deduplicated',async()=>{await request('/api/create_document.php',{cookie:owner,form:form({...values,formtype:'edit_document',doc_id:doc,doc_type:'คำสั่ง',file_id:[0],doc_file_name:[]})});const send=()=>request('/email_send/process_pdf.php',{cookie:admin,data:{doc_id:doc,file_name:fileName,doc_year:2569}});const first=await send();assert.match(first.text,/"successful":1/);const second=await send();assert.match(second.text,/"successful":0/);});
 await test('private static paths blocked',async()=>{for(const path of ['/email_send/User_Data.json','/config/config.php']){const result=await request(path,{status:remote?[403,302]:403});if(result.r.status===302)assert.equal(new URL(result.r.headers.get('Location'),base).port,'2222','Only hosting access-denied redirect is accepted');}});
 await test('outbox worker records mocked SMTP/push',async()=>{cli('scripts/notifications.php');const rows=inspect('outbox','');assert.ok(rows.some(r=>r.payload.type==='mail'&&r.payload.email==='qa-recipient@siya.ac.th'));assert.ok(rows.some(r=>r.payload.type==='push'&&r.payload.user_id===seed.users.recipient));assert.ok(rows.some(r=>r.payload.type==='drive_image'));});
 await test('logout revokes server session and returns JSON only',async()=>{const r=await request('/api/logout.php',{cookie:owner,data:{}});assert.equal(r.body.status,'success');await request('/api/get_data_send.php',{cookie:owner,data:{Year:2569},status:401});});
 console.log(`Integration: ${passed} passed`);
 console.log(JSON.stringify({doc,fileName,users:seed.users,storage:remote?'private storage on staging host':env.EOFFICE_STORAGE}));
}
run().catch(e=>{console.error(e);console.error(serverErrors);process.exitCode=1;}).finally(()=>servers.forEach(server=>server.kill()));
